name: Application Inspector

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:
  analyze:
    name: analyze code
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: microsoft/ApplicationInspector-Action@v1
        with:
          file-path-exclusions: '"none"'
      - uses: actions/upload-artifact@v2
        with:
          name: AppInspectorResults
          path: AppInspectorResults.json
