name: Application Inspector

on:
  push:
    branches: 'main'
  pull_request:
    branches: 'main'
  workflow_dispatch:

jobs:
  analyze:
    name: analyze code
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Execute scan
        uses: microsoft/ApplicationInspector-Action@v1
        with:
          output-format: 'sarif'
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AppInspectorResults
          path: AppInspectorResults.sarif
